name: Build and push Docker image
description: 'Build and push the Docker image'
inputs:
  AWS_ACCESS_KEY_ID:
    description: AWS secret key ID
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: AWS secret access key
    required: true
  VERSION:
    description: Version to tag the image with
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          registry: 456480488550.dkr.ecr.eu-west-1.amazonaws.com
          username: ${{ inputs.AWS_ACCESS_KEY_ID }}
          password: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    - name: Build
      shell: bash
      run: docker build -t logstash:${{ inputs.VERSION }} --build-arg LOGSTASH_PLUGINS=logstash-output-opensearch .
    - name: Tag
      shell: bash
      run: docker tag logstash:${{ inputs.VERSION }} 456480488550.dkr.ecr.eu-west-1.amazonaws.com/logstash:${{ inputs.VERSION }}
    - name: Push
      shell: bash
      run: |
        set +e
        if docker manifest inspect 456480488550.dkr.ecr.eu-west-1.amazonaws.com/logstash:${{ inputs.VERSION }}; then
          echo "Image does exist, not attempting a push"
        else
          set -e
          docker push 456480488550.dkr.ecr.eu-west-1.amazonaws.com/logstash:${{ inputs.VERSION }}
        fi
