name: Merge to carepay-custom

env:
  AWS_REGION: eu-west-1
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# Controls when the workflow will run
on:
  push:
    branches:
      - carepay-custom
  workflow_dispatch:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and push docker image
        uses: ./.github/actions/build-and-push-docker-image
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VERSION: 8.15.3

